name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: shimataro/ssh-key-action@v2.4.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 13.50.251.170

    - name: Deploy application to EC2
      run: |
        echo "Hi from ec2"
