name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: shimataro/ssh-key-action@v2.4.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 13.50.251.170

    - name: Copy files to EC2 
      run: | 
        scp -o StrictHostKeyChecking=no -r . ubuntu@13.50.251.170:/home/ubuntu/app/
    - name: Deploy application to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.50.251.170 << 'EOF' 
          ls -la ~/app
        EOF
